"""
============== UniBo: AI and Robotics 2025 ==============
Base code: simple knowledge graph, primitives to manage a knowledge graph and reason with it
To be extended by the students for Lab 5

(c) 2024-2025 Alessandro Saffiotti
"""
import sys

# libraries to handle triples and graphs
from rdflib import Graph, Namespace, URIRef, Literal
from rdflib.namespace import RDFS, RDF

# libraries to handle reasoning
from owlrl import DeductiveClosure, OWLRL_Semantics

""" Loading Graphs"""

class KnowledgeGraph:
    def __init__(self, ttl_file = "./air-environment.ttl"):

        # utility variable : list of namespaces that we will need for querying
        self.namespaces = {'rdf': RDF, 'rdfs' : RDFS, "ex": 'http://example.org/'}

        # initialise new graphs : asserted (triples stated in the ttl file), inferred (triples generated by the reasoner)
        self.asserted = Graph().parse(ttl_file)
        self.expanded = Graph().parse(ttl_file)
        self.inferred = Graph()

    def get_info(self):
        """
        Get the number of triples the graph contains
        """
        print("Asserted Graph has %s statements." % len(self.asserted))
        print("Inferred Graph has %s statements." % len(self.inferred))
        print("Expanded Graph has %s statements." % len(self.expanded))

    def add(self, subj, pred, obj): 
            """
            Adding a gvein <subj, pred, obj> triple, eg: <bed1 is_located_in room1>
            For pred use:
            - 'type' to create new instance of a class (eg, bed_3 is of type Bed)
            - 'subclass_of' to create a new subclass of a class (eg, the class Bed is a subclass of Furniture)
            """
            sdata = self.namespaces['ex'] + subj
            if (pred == "type"):
                pdata = RDF.type
            elif(pred == "subclass_of"):
                 pdata = RDFS.subClassOf
            else:
                 pdata = self.namespaces['ex'] + pred
            odata = self.namespaces['ex'] + obj
            print("Adding " + str((URIRef(sdata),URIRef(pdata) , URIRef(odata))))
            self.asserted.add((URIRef(sdata),URIRef(pdata) , URIRef(odata)))
            self.expanded.add((URIRef(sdata),URIRef(pdata) , URIRef(odata)))

    def save_graph(self, filename):
         """
         Save the knowledge graph to a Turtle file
         """
         filename = "./" + filename + ".ttl"
         self.expanded.serialize(destination=filename, format= "ttl")
         print("Saving asserted graph to file %s" % filename)

    def remove(self, subj, pred, obj): 
            """
            Remove a given <subj, pred, obj> triple from the graph
            """
            sdata = self.namespaces['ex'] + subj
            if (pred == "type"):
                pdata = RDF.type
            elif(pred == "subclass_of"):
                 pdata = RDFS.subClassOf
            else:
                 pdata = self.namespaces['ex'] + pred
            odata = self.namespaces['ex'] + obj
            print("Remove " + str((URIRef(sdata),URIRef(pdata) , URIRef(odata))))
            self.asserted.remove((URIRef(sdata),URIRef(pdata) , URIRef(odata)))
            self.expanded.remove((URIRef(sdata),URIRef(pdata) , URIRef(odata)))

    def reason(self): 
          DeductiveClosure(OWLRL_Semantics).expand(self.expanded)   # now self.asserted is expanded (asserted + inferred triples)
          self.inferred = self.expanded - self.asserted             # compute the diff between expanded and asserted
          self.get_info()

    def query_entity_types(self, entity, reasoning):
        """
        Return the type of an entity, as asserted or as inferred by reasoning
        """
        query_reasoning = "select ?type where { ex:"+entity+" rdf:type ?type.}" 
        
        # querying asserted graph
        if (not reasoning):
             res_reasoning = self.asserted.query(query_reasoning, initNs=self.namespaces)
        else:
             res_reasoning = self.inferred.query(query_reasoning, initNs=self.namespaces)
        return list(res_reasoning)
     
    def objects_in_room(self, room, reasoning=False):
        query_reasoning = "select ?object where { ex:" + room + " ex:contains ?object. }" 
        # querying asserted graph
        if(not reasoning):
            objects = self.asserted.query(query_reasoning, initNs=self.namespaces)
        else:
             objects = self.inferred.query(query_reasoning, initNs=self.namespaces)
        #print(list(objects))
        return list(objects)

    def object_status(self, door,  status): 
        query_reasoning = "ask { ex:" + door +" ex:hasStatus \'" + str(status).lower() +"\'}"
        # querying asserted graph
        objects = self.asserted.query(query_reasoning, initNs=self.namespaces)
 
        print(list(objects))
        return list(objects)
    
    def object_room(self, obj, reasoning = False):
        query_reasoning = "select ?l where { ex:"+ obj + " ex:hasLocation ?l } "
        # querying asserted graph
        if (not reasoning ):
            result = self.asserted.query(query_reasoning, initNs=self.namespaces)
        else:
            result = self.inferred.query(query_reasoning, initNs=self.namespaces)
        room = list(result)
        return room

        

def test():
    """Let's see how many triples the graph contains"""
    kg = KnowledgeGraph()
    #kg.reason()
    #kg.query_entity_types("room2")
    #print(kg.objects_in_room("room1", True))
    #print(kg.objects_in_room("room1", True))
    result = kg.object_room("box2")
    old_room = result[0]
    old_room = str(old_room).split("/")[-1][:-4]
    kg.remove("box2", "hasLocation", old_room)
    kg.add("box2", "hasLocation", "wardrobe1")
    kg.reason()
    result2 = kg.object_room("box2", True)
    result2.extend(kg.object_room("box2", False))
    if(len(result2)) >0:
            new_location = list(result2)[0]
            new_location = str(new_location).split("/")[-1][:-4]
    print(new_location)


    # print the length of the graph

if __name__ == "__main__":
    test()
